### PR TITLE
Massive update with many, many settings in ini

### PR DESCRIPTION
**Pull request by misteraddons**

### CODE REVIEW

**Comment by MAME-GETTER** [comment]
Will be reviewing this over the next few days.

**Comment by misteraddons** [comment]
Cool, let me know if you have any questions! I've done fairly thorough testing.

**Comment by MAME-GETTER** [comment]
Can the region be fixed to do USA rather than US?

**Comment by MAME-GETTER** [comment]
Can region be sorted by core or platform?

**Comment by misteraddons** [comment]
> Can the region be fixed to do USA rather than US?
I'm not sure what you mean - the region folders are made from the MRA tags. Do you want to create an exception to catch "US" and rename it to "USA"?

> Can region be sorted by core or platform or manufacture?
Do you mean something like this?
_Region
    _World
        _Core
        _Manufacturer
        _Platform

Or do you mean this?
_Core
    _jtcps2
        _World
_Manufacturer
    _Capcom
        _World
_Platform
    _CPS2
        _World

**Comment by MAME-GETTER** [comment]
#I'm not sure what you mean - the region folders are made from the MRA tags. Do you want to create an exception to catch "US" and rename it to "USA"?

Yes, I want to avoid this: 
Screenshot from 2021-06-25 09-59-14

I prefer this sort:

```
_Region
     _World
         _Core
         _Manufacturer
         _Platform

```

**Comment by misteraddons** [comment]
Done

**Comment by MAME-GETTER** [comment]
After this last weekend and our chats on discord for the new AO based on a AOD. I think it would be best to hold on this PR.

If after some time passes and there is no movement on the AOD and new AO then I will except this PR. 

Meanwhile, I will leave this PR open as a sign of good faith.

**Pull request merged**
